### PR TITLE
XR_KHR_convert_timespec_time: fix typos

### PR DESCRIPTION
**Pull request by bl4ckb0ne**
`XR_KHR_convert_timespec_time` was referring to the timespec argument as `timespecTime` in the functions signatures, and `unixTime` in the documentation.

I chose to change it to `ts` when fixing it, as it is how the `struct timespec` is commonly referred to.

### CODE REVIEW

**Comment by rpavlik** [comment]
Good catch!

 I'd be more comfortable merging (without additional WG approval) a patch that just updates the .adoc file to match the xml (timespecTime), which is the canonical representation of the API. (Isn't `ts` usually the structure, though, rather than a pointer, anyway?)

**Comment by bl4ckb0ne** [comment]
I usually use/see `struct timespec *ts` out there, but I made the change to use `timespecTime` everywhere.

**Review by rpavlik — APPROVED** [review]

**Comment by bl4ckb0ne** [comment]
Seems to be an issue with the CI: "Error: HttpError: Resource not accessible by integration".
Did I missed enabling something somewhere?

**Comment by rpavlik** [comment]
We don't merge directly to master in this repo.

**Pull request merged**
