### PR TITLE
Reserve extension 48 for XR_MND_egl_enable

### PR DESCRIPTION
**Pull request by emersion**
This new extension will enable EGL.

### CODE REVIEW

**Comment by ddevault** [comment]
Please hold on merging this while we discuss it in greater detail.

**Comment by ddevault** [comment]
Okay, we're ready to have this merged.

**Comment by emersion** [comment]
Renamed to `XR_MND_egl_enable`.

**Comment by ddevault** [comment]
Bump. This should be merged ASAP.

**Comment by emersion** [comment]
cc @rpavlik

**Comment by rpavlik** [comment]
This reservation will be reserved, though the extension number will probably differ due to collision with internal changes.

**Comment by rpavlik** [comment]
It will actually be number 49 in the upcoming patch release.

**Pull request merged**
