### PR TITLE
Proposal for the Huawei vendor extension

### PR DESCRIPTION
**Pull request by rachelhuang**
A new adoc file is added. The supported status is changed from "disable" to "openxr". Let me know if there's any problem.

### CODE REVIEW

**Comment by rachelhuang** [comment]
@rpavlik Didn't receive any response. Just ping you again...Let me know if there's anything wrong. Thanks.

**Comment by rpavlik** [comment]
Ah, I just noticed when I went to merge, it is missing the "Last Modified Date" header as well as the "IP Status" header.

Additionally, since we need to wait for those for merging, I want to offer you the opportunity to make the name more specific than "controller" for your path - it's not required, of course, but it may be useful when you come up with a new model of controller in the future.

For example, other vendors have essentially repeated the product name in front: vive_controller, index_controller, while some others have actual distinct names for their controllers (the "Oculus Touch" controller -> "touch_controller").

**Comment by rachelhuang** [comment]
@rpavlik Thanks, will modify it soon. As for the name, we have already considered and decided to leave as it is, since we'd want it to be more general enough for our products:).

**Comment by rachelhuang** [comment]
@rpavlik done. Please check it and let me know if it's ready for merging.

**Comment by rpavlik** [comment]
@rachelhuang :

Can you submit an additional pull request to add the correct copyright/license header for the extension file would be?  My best guess is to add the following.

```
// Copyright (c) 2020 Huawei
//
// SPDX-License-Identifier: CC-BY-4.0
```

Please correct the copyright statement as required. (I believe the license there is mandatory/part of the Contributor License Agreement: the entire specification source is licensed as CC-BY-4.0)

**Comment by rachelhuang** [comment]
@rpavlik :

Okay. Is it because we submited the extesion during the membership suspension? as other extension files don't have the copyright headers last time I checked.

**Comment by rpavlik** [comment]
@rachelhuang :

No, I'm asking everyone to add the copyright headers. Most of the files now have them, I'm working on the vendor extensions now. Everybody with extensions got an issue/message from me about it.  (Vulkan recently did the same thing)

**Comment by rachelhuang** [comment]
@rpavlik :

Just to make sure I understand it correctly. Does it mean that every vendor extension should include the CC-BY-4.0?

**Comment by rpavlik** [comment]
Yes, that's correct. If that doesn't work for you, I'll have to bring somebody in who knows the Khronos CLA better than I do.

**Comment by rachelhuang** [comment]
Got it. Thanks. Will modify and submit it today.

**Pull request merged**
