### PR TITLE
Register Deep Mirror for author id

### PR DESCRIPTION
**Pull request by lyh-dm**
Register Deep Mirror for author id

### CODE REVIEW

**Comment by rpavlik** [comment]
Are you making a runtime, or an API layer, out of curiosity?

**Comment by lyh-dm** [comment]
@rpavlik I want to create some extensions for our device.

**Comment by lyh-dm** [comment]
Hi @rpavlik , could you please help to review this PR? Thanks.
Oh sorry, seems I misunderstand your last question. We want to implement the extension functions in a new API layer. If I understand correctly, we need such an author ID to register these new functions and new data struct to the OpenXR-SDK.

**Comment by rpavlik** [comment]
Yep, this is right for creating new extensions. Most of the time extensions are implemented in the runtime itself, but some can be implemented in extensions if that works better for the use case.

**Review by rpavlik — APPROVED** [review]

**Pull request merged**
