### PR TITLE
Register and reserve 5 extensions for danwillm

### PR DESCRIPTION
**Pull request by danwillm**

### CODE REVIEW

**Comment by rpavlik** [comment]
I assume these will be for API layer provided extensions?

**Review by rpavlik — APPROVED** [review]
Let me know what you need them for and I'll merge this. I've adjusted the reservation slightly to avoid conflicts.

**Comment by danwillm** [comment]
Experimenting with a device plugin extension 😄

**Comment by rpavlik** [comment]
sounds good!

**Pull request merged**
